# Generated by Django 3.1.5 on 2021-01-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_autor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
